[package]
name = "asl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data_structures={path="src/data_structures"}
frontend={path="src/frontend"}

[[bin]]
name="asc"
path="src/asc/src/main.rs"